name: Simple_CD/CD_Action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Check_head
      run: |
           echo " Check Ok!!"
           echo "ready Step 1 !! OK"
    - name : setup net for build
      uses: actions/checkout@v3
      with: 
        dotnet-sersion: 8.0.x
    - name : build Soure
      working-directory: /home/debian_dev/actions-runner/_work/CI-CD_Simple/CI-CD_Simple/
      run: |
        docker-compose up -d --build
